senzing-garage/sz-sdk-python

.github/workflows/build-distribution.yaml, .github/workflows/isort.yaml, .github/workflows/publish-to-pypi.yaml, CHANGELOG.md
=> #3 Prepare for versioned release

CHANGELOG.md, Makefile, setup.cfg, src/senzing_abstract/g2config_abstract.py, src/senzing_abstract/g2configmgr_abstract.py, src/senzing_abstract/g2diagnostic_abstract.py, src/senzing_abstract/g2engine_abstract.py, src/senzing_abstract/g2helpers.py, src/senzing_abstract/g2product_abstract.py, tests/g2config_test.py
=> 3.dockter.6

.github/linters/.yaml-lint.yml, .github/workflows/add-labels-standardized.yaml, .github/workflows/add-to-project-garage-dependabot.yaml, .github/workflows/add-to-project-garage.yaml, .github/workflows/build-distribution.yaml, .github/workflows/create-sphinx-documentation.yaml, .github/workflows/dependabot-approve-and-merge.yaml, .github/workflows/flake8.yaml, .github/workflows/isort.yaml, .github/workflows/lint-workflows.yaml, .github/workflows/publish-to-pypi.yaml, .github/workflows/pylint.yaml, .github/workflows/pytest-darwin.yaml.disabled, .github/workflows/pytest-linux.yaml, .github/workflows/pytest-windows.yaml, .github/workflows/python-code-quality.yaml, .github/workflows/unittest-linux.yaml
Issue number: senzing-factory/build-resources#69
=> senzing-factory/build-resources#69 add linting

CHANGELOG.md, setup.cfg, src/senzing_abstract/szabstractfactory_abstract.py, src/senzing_abstract/szconfig_abstract.py, src/senzing_abstract/szconfigmanager_abstract.py, src/senzing_abstract/szdiagnostic_abstract.py, src/senzing_abstract/szengine_abstract.py, src/senzing_abstract/szhelpers.py, src/senzing_abstract/szproduct_abstract.py
=> #64 Add help() method

README.md
=> 64 dockter 2

CHANGELOG.md, README.md, docs/source/senzing_abstract.rst
=> #64 Add help

CHANGELOG.md, src/senzing_abstract/szengine_abstract.py, tests/szengine_test.py
=> #75 Add preprocess_record()

setup.cfg
=> #75 Update package version

src/senzing_abstract/szdiagnostic_abstract.py
=> #118 Add documentation for get_feature()

setup.cfg
=> #127 Update pip version

setup.cfg
=> #149 Bump version

src/senzing/szengineflags.py
=> #172 Add engine flags

.github/workflows/bearer.yaml
=> #233 add bearer

.github/workflows/pytest-darwin.yaml, .github/workflows/pytest-linux.yaml, .github/workflows/pytest-windows.yaml
=> #250 nightly cron job for install testing

.github/workflows/pytest-darwin.yaml, .github/workflows/pytest-linux.yaml, .github/workflows/pytest-windows.yaml
=> remove coverage from slack notifications

CHANGELOG.md, documentation-requirements.txt, examples/szengine/preprocess_record.py, setup.cfg
=> #280 - Fix flag in examples/szengine/preprocess_record.py

CHANGELOG.md, setup.cfg, src/senzing/szengineflags.py
=> #246 Add SZ_REDO_DEFAULT_FLAGS

documentation-requirements.txt
=> #309 unpin spinx-tabs minor version

CHANGELOG.md, examples/szabstractfactory/destroy.py, examples/szabstractfactory/destroy.txt, setup.cfg, src/senzing/szabstractfactory.py, src/senzing_mock/senzing_mock.py, tests/szabstractfactory_test.py
=> #313 Add SzAbstractFactory.Destroy()

docs/source/senzing.rst, src/senzing/szabstractfactory.py
=> #298 Add implementations

CHANGELOG.md, setup.cfg, src/senzing/constants.py, src/senzing/szabstractfactory.py, src/senzing/szconfig.py, src/senzing/szconfigmanager.py, src/senzing/szdiagnostic.py, src/senzing/szengine.py, src/senzing/szengineflags.py, src/senzing/szerror.py, src/senzing/szproduct.py
=> #298 Update documentation

CHANGELOG.md, setup.cfg, src/senzing/constants.py, src/senzing/szabstractfactory.py, src/senzing/szconfig.py, src/senzing/szconfigmanager.py, src/senzing/szdiagnostic.py, src/senzing/szengine.py, src/senzing/szengineflags.py, src/senzing/szerror.py, src/senzing/szproduct.py
=> #345 - Update all method doc strings for raises

.github/workflows/pytest-darwin.yaml, .github/workflows/pytest-linux.yaml, .github/workflows/pytest-windows.yaml
=> #354 4.0 updates, switch from beta to staging, test prod

CHANGELOG.md, src/senzing/szengine.py
=> #374 Improve count_redo_records comment
